# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_eclipse_microprofile_openapi_models_media_xml import OrgEclipseMicroprofileOpenapiModelsMediaXML  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgEclipseMicroprofileOpenapiModelsMediaXML(unittest.TestCase):
    """OrgEclipseMicroprofileOpenapiModelsMediaXML unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgEclipseMicroprofileOpenapiModelsMediaXML(self):
        """Test OrgEclipseMicroprofileOpenapiModelsMediaXML"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_eclipse_microprofile_openapi_models_media_xml.OrgEclipseMicroprofileOpenapiModelsMediaXML()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
