# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.jobs_api import JobsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dismiss1(self):
        """Test case for dismiss1

        cancel a job execution, remove a finished job  # noqa: E501
        """
        pass

    def test_execute1(self):
        """Test case for execute1

        Execute a process.  # noqa: E501
        """
        pass

    def test_get_logs1(self):
        """Test case for get_logs1

        Retrieve logs of a job  # noqa: E501
        """
        pass

    def test_get_status1(self):
        """Test case for get_status1

        Retrieve the information about a job (status, results)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
