# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.be_spacebel_altius_processing_transactional_model_exception_report_type import BeSpacebelAltiusProcessingTransactionalModelExceptionReportType  # noqa: E501
from swagger_client.rest import ApiException


class TestBeSpacebelAltiusProcessingTransactionalModelExceptionReportType(unittest.TestCase):
    """BeSpacebelAltiusProcessingTransactionalModelExceptionReportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeSpacebelAltiusProcessingTransactionalModelExceptionReportType(self):
        """Test BeSpacebelAltiusProcessingTransactionalModelExceptionReportType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.be_spacebel_altius_processing_transactional_model_exception_report_type.BeSpacebelAltiusProcessingTransactionalModelExceptionReportType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
