# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.be_spacebel_altius_processing_transactional_model_landing_page import BeSpacebelAltiusProcessingTransactionalModelLandingPage  # noqa: E501
from swagger_client.rest import ApiException


class TestBeSpacebelAltiusProcessingTransactionalModelLandingPage(unittest.TestCase):
    """BeSpacebelAltiusProcessingTransactionalModelLandingPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeSpacebelAltiusProcessingTransactionalModelLandingPage(self):
        """Test BeSpacebelAltiusProcessingTransactionalModelLandingPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.be_spacebel_altius_processing_transactional_model_landing_page.BeSpacebelAltiusProcessingTransactionalModelLandingPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
