# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_eclipse_microprofile_openapi_models_media_discriminator import OrgEclipseMicroprofileOpenapiModelsMediaDiscriminator  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgEclipseMicroprofileOpenapiModelsMediaDiscriminator(unittest.TestCase):
    """OrgEclipseMicroprofileOpenapiModelsMediaDiscriminator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgEclipseMicroprofileOpenapiModelsMediaDiscriminator(self):
        """Test OrgEclipseMicroprofileOpenapiModelsMediaDiscriminator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_eclipse_microprofile_openapi_models_media_discriminator.OrgEclipseMicroprofileOpenapiModelsMediaDiscriminator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
