# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_eclipse_microprofile_openapi_models_responses_api_responses import OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponses  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgEclipseMicroprofileOpenapiModelsResponsesAPIResponses(unittest.TestCase):
    """OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgEclipseMicroprofileOpenapiModelsResponsesAPIResponses(self):
        """Test OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_eclipse_microprofile_openapi_models_responses_api_responses.OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
