# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_get_checks1(self):
        """Test case for get_checks1

        """
        pass

    def test_get_json123(self):
        """Test case for get_json123

        """
        pass

    def test_get_json12345(self):
        """Test case for get_json12345

        """
        pass

    def test_get_metadata12(self):
        """Test case for get_metadata12

        """
        pass

    def test_get_metadata123(self):
        """Test case for get_metadata123

        """
        pass

    def test_get_text12345(self):
        """Test case for get_text12345

        """
        pass


if __name__ == '__main__':
    unittest.main()
