# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.legacy_api import LegacyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLegacyApi(unittest.TestCase):
    """LegacyApi unit test stubs"""

    def setUp(self):
        self.api = LegacyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_landing_page(self):
        """Test case for get_landing_page

        landing page of this API  # noqa: E501
        """
        pass

    def test_get_requirements_classes(self):
        """Test case for get_requirements_classes

        information about standards that this API conforms to (optional implementation in ALTIUS)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
