# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.be_spacebel_altius_processing_transactional_model_req_classes import BeSpacebelAltiusProcessingTransactionalModelReqClasses  # noqa: E501
from swagger_client.rest import ApiException


class TestBeSpacebelAltiusProcessingTransactionalModelReqClasses(unittest.TestCase):
    """BeSpacebelAltiusProcessingTransactionalModelReqClasses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeSpacebelAltiusProcessingTransactionalModelReqClasses(self):
        """Test BeSpacebelAltiusProcessingTransactionalModelReqClasses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.be_spacebel_altius_processing_transactional_model_req_classes.BeSpacebelAltiusProcessingTransactionalModelReqClasses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
