# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.be_spacebel_altius_processing_model_execution_request import BeSpacebelAltiusProcessingModelExecutionRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestBeSpacebelAltiusProcessingModelExecutionRequest(unittest.TestCase):
    """BeSpacebelAltiusProcessingModelExecutionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBeSpacebelAltiusProcessingModelExecutionRequest(self):
        """Test BeSpacebelAltiusProcessingModelExecutionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.be_spacebel_altius_processing_model_execution_request.BeSpacebelAltiusProcessingModelExecutionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
