# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_eclipse_microprofile_openapi_models_media_media_type import OrgEclipseMicroprofileOpenapiModelsMediaMediaType  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgEclipseMicroprofileOpenapiModelsMediaMediaType(unittest.TestCase):
    """OrgEclipseMicroprofileOpenapiModelsMediaMediaType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgEclipseMicroprofileOpenapiModelsMediaMediaType(self):
        """Test OrgEclipseMicroprofileOpenapiModelsMediaMediaType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_eclipse_microprofile_openapi_models_media_media_type.OrgEclipseMicroprofileOpenapiModelsMediaMediaType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
