# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BeSpacebelAltiusProcessingTransactionalModelLandingPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'links': 'list[BeSpacebelAltiusProcessingTransactionalModelLink]',
        'title': 'str'
    }

    attribute_map = {
        'description': 'description',
        'links': 'links',
        'title': 'title'
    }

    def __init__(self, description=None, links=None, title=None):  # noqa: E501
        """BeSpacebelAltiusProcessingTransactionalModelLandingPage - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._links = None
        self._title = None
        self.discriminator = None
        if description is not None:
            self.description = description
        self.links = links
        if title is not None:
            self.title = title

    @property
    def description(self):
        """Gets the description of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501


        :return: The description of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.


        :param description: The description of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def links(self):
        """Gets the links of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501


        :return: The links of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501
        :rtype: list[BeSpacebelAltiusProcessingTransactionalModelLink]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.


        :param links: The links of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501
        :type: list[BeSpacebelAltiusProcessingTransactionalModelLink]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def title(self):
        """Gets the title of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501


        :return: The title of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.


        :param title: The title of this BeSpacebelAltiusProcessingTransactionalModelLandingPage.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BeSpacebelAltiusProcessingTransactionalModelLandingPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeSpacebelAltiusProcessingTransactionalModelLandingPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
