# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BeSpacebelAltiusProcessingTransactionalModelLink(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rel': 'str',
        'href': 'str',
        'type': 'str',
        'title': 'str'
    }

    attribute_map = {
        'rel': 'rel',
        'href': 'href',
        'type': 'type',
        'title': 'title'
    }

    def __init__(self, rel=None, href=None, type=None, title=None):  # noqa: E501
        """BeSpacebelAltiusProcessingTransactionalModelLink - a model defined in Swagger"""  # noqa: E501
        self._rel = None
        self._href = None
        self._type = None
        self._title = None
        self.discriminator = None
        if rel is not None:
            self.rel = rel
        self.href = href
        if type is not None:
            self.type = type
        if title is not None:
            self.title = title

    @property
    def rel(self):
        """Gets the rel of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501


        :return: The rel of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this BeSpacebelAltiusProcessingTransactionalModelLink.


        :param rel: The rel of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :type: str
        """

        self._rel = rel

    @property
    def href(self):
        """Gets the href of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501


        :return: The href of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this BeSpacebelAltiusProcessingTransactionalModelLink.


        :param href: The href of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def type(self):
        """Gets the type of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501


        :return: The type of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BeSpacebelAltiusProcessingTransactionalModelLink.


        :param type: The type of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def title(self):
        """Gets the title of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501


        :return: The title of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BeSpacebelAltiusProcessingTransactionalModelLink.


        :param title: The title of this BeSpacebelAltiusProcessingTransactionalModelLink.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BeSpacebelAltiusProcessingTransactionalModelLink, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BeSpacebelAltiusProcessingTransactionalModelLink):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
