# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsPaths(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '': 'OrgEclipseMicroprofileOpenapiModelsPathItem',
        'path_items': 'list[object]',
        'path_item': 'OrgEclipseMicroprofileOpenapiModelsPathItem'
    }

    attribute_map = {
        'path_items': 'pathItems',
        'path_item': 'pathItem'
    }

    def __init__(self, path_items=None, path_item=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsPaths - a model defined in Swagger"""  # noqa: E501
        self._ = None
        self._path_items = None
        self._path_item = None
        self.discriminator = None

        if path_items is not None:
            self.path_items = path_items
        if path_item is not None:
            self.path_item = path_item

    @property
    def path_items(self):
        """Gets the path_items of this OrgEclipseMicroprofileOpenapiModelsPaths.  # noqa: E501


        :return: The path_items of this OrgEclipseMicroprofileOpenapiModelsPaths.  # noqa: E501
        :rtype: list[object]
        """
        return self._path_items

    @path_items.setter
    def path_items(self, path_items):
        """Sets the path_items of this OrgEclipseMicroprofileOpenapiModelsPaths.


        :param path_items: The path_items of this OrgEclipseMicroprofileOpenapiModelsPaths.  # noqa: E501
        :type: list[object]
        """

        self._path_items = path_items

    @property
    def path_item(self):
        """Gets the path_item of this OrgEclipseMicroprofileOpenapiModelsPaths.  # noqa: E501


        :return: The path_item of this OrgEclipseMicroprofileOpenapiModelsPaths.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsPathItem
        """
        return self._path_item

    @path_item.setter
    def path_item(self, path_item):
        """Sets the path_item of this OrgEclipseMicroprofileOpenapiModelsPaths.


        :param path_item: The path_item of this OrgEclipseMicroprofileOpenapiModelsPaths.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsPathItem
        """

        self._path_item = path_item

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsPaths, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsPaths):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
