# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '': 'list[str]',
        'scheme': 'list[str]',
        'schemes': 'list[object]'
    }

    attribute_map = {
        'scheme': 'scheme',
        'schemes': 'schemes'
    }

    def __init__(self, scheme=None, schemes=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement - a model defined in Swagger"""  # noqa: E501
        self._ = None
        self._scheme = None
        self._schemes = None
        self.discriminator = None
		
        if scheme is not None:
            self.scheme = scheme
        if schemes is not None:
            self.schemes = schemes


    @property
    def scheme(self):
        """Gets the scheme of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.  # noqa: E501


        :return: The scheme of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.  # noqa: E501
        :rtype: list[str]
        """
        return self._scheme

    @scheme.setter
    def scheme(self, scheme):
        """Sets the scheme of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.


        :param scheme: The scheme of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.  # noqa: E501
        :type: list[str]
        """

        self._scheme = scheme

    @property
    def schemes(self):
        """Gets the schemes of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.  # noqa: E501


        :return: The schemes of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.  # noqa: E501
        :rtype: list[object]
        """
        return self._schemes

    @schemes.setter
    def schemes(self, schemes):
        """Sets the schemes of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.


        :param schemes: The schemes of this OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement.  # noqa: E501
        :type: list[object]
        """

        self._schemes = schemes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsSecuritySecurityRequirement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
