# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsInfoInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'license': 'OrgEclipseMicroprofileOpenapiModelsInfoLicense',
        'contact': 'OrgEclipseMicroprofileOpenapiModelsInfoContact',
        'description': 'str',
        'terms_of_service': 'str',
        'title': 'str',
        'version': 'str'
    }

    attribute_map = {
        'license': 'license',
        'contact': 'contact',
        'description': 'description',
        'terms_of_service': 'termsOfService',
        'title': 'title',
        'version': 'version'
    }

    def __init__(self, license=None, contact=None, description=None, terms_of_service=None, title=None, version=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsInfoInfo - a model defined in Swagger"""  # noqa: E501
        self._license = None
        self._contact = None
        self._description = None
        self._terms_of_service = None
        self._title = None
        self._version = None
        self.discriminator = None
        if license is not None:
            self.license = license
        if contact is not None:
            self.contact = contact
        if description is not None:
            self.description = description
        if terms_of_service is not None:
            self.terms_of_service = terms_of_service
        if title is not None:
            self.title = title
        if version is not None:
            self.version = version

    @property
    def license(self):
        """Gets the license of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501


        :return: The license of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsInfoLicense
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.


        :param license: The license of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsInfoLicense
        """

        self._license = license

    @property
    def contact(self):
        """Gets the contact of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501


        :return: The contact of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsInfoContact
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.


        :param contact: The contact of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsInfoContact
        """

        self._contact = contact

    @property
    def description(self):
        """Gets the description of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501


        :return: The description of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.


        :param description: The description of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def terms_of_service(self):
        """Gets the terms_of_service of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501


        :return: The terms_of_service of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :rtype: str
        """
        return self._terms_of_service

    @terms_of_service.setter
    def terms_of_service(self, terms_of_service):
        """Sets the terms_of_service of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.


        :param terms_of_service: The terms_of_service of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :type: str
        """

        self._terms_of_service = terms_of_service

    @property
    def title(self):
        """Gets the title of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501


        :return: The title of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.


        :param title: The title of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def version(self):
        """Gets the version of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501


        :return: The version of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.


        :param version: The version of this OrgEclipseMicroprofileOpenapiModelsInfoInfo.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsInfoInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsInfoInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
