# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsParametersParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'schema': 'OrgEclipseMicroprofileOpenapiModelsMediaSchema',
        'allow_reserved': 'bool',
        '_in': 'str',
        'deprecated': 'bool',
        'description': 'str',
        'required': 'bool',
        'content': 'OrgEclipseMicroprofileOpenapiModelsMediaContent',
        'example': 'JavaLangObject',
        'examples': 'list[object]',
        'explode': 'bool',
        'allow_empty_value': 'bool',
        'name': 'str',
        'style': 'str'
    }

    attribute_map = {
        'schema': 'schema',
        'allow_reserved': 'allowReserved',
        '_in': 'in',
        'deprecated': 'deprecated',
        'description': 'description',
        'required': 'required',
        'content': 'content',
        'example': 'example',
        'examples': 'examples',
        'explode': 'explode',
        'allow_empty_value': 'allowEmptyValue',
        'name': 'name',
        'style': 'style'
    }

    def __init__(self, schema=None, allow_reserved=None, _in=None, deprecated=None, description=None, required=None, content=None, example=None, examples=None, explode=None, allow_empty_value=None, name=None, style=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsParametersParameter - a model defined in Swagger"""  # noqa: E501
        self._schema = None
        self._allow_reserved = None
        self.__in = None
        self._deprecated = None
        self._description = None
        self._required = None
        self._content = None
        self._example = None
        self._examples = None
        self._explode = None
        self._allow_empty_value = None
        self._name = None
        self._style = None
        self.discriminator = None
        if schema is not None:
            self.schema = schema
        if allow_reserved is not None:
            self.allow_reserved = allow_reserved
        if _in is not None:
            self._in = _in
        if deprecated is not None:
            self.deprecated = deprecated
        if description is not None:
            self.description = description
        if required is not None:
            self.required = required
        if content is not None:
            self.content = content
        if example is not None:
            self.example = example
        if examples is not None:
            self.examples = examples
        if explode is not None:
            self.explode = explode
        if allow_empty_value is not None:
            self.allow_empty_value = allow_empty_value
        if name is not None:
            self.name = name
        if style is not None:
            self.style = style

    @property
    def schema(self):
        """Gets the schema of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The schema of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsMediaSchema
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param schema: The schema of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsMediaSchema
        """

        self._schema = schema

    @property
    def allow_reserved(self):
        """Gets the allow_reserved of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The allow_reserved of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: bool
        """
        return self._allow_reserved

    @allow_reserved.setter
    def allow_reserved(self, allow_reserved):
        """Sets the allow_reserved of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param allow_reserved: The allow_reserved of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: bool
        """

        self._allow_reserved = allow_reserved

    @property
    def _in(self):
        """Gets the _in of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The _in of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self.__in

    @_in.setter
    def _in(self, _in):
        """Sets the _in of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param _in: The _in of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: str
        """
        allowed_values = ["path", "query", "header", "cookie"]  # noqa: E501
        if _in not in allowed_values:
            raise ValueError(
                "Invalid value for `_in` ({0}), must be one of {1}"  # noqa: E501
                .format(_in, allowed_values)
            )

        self.__in = _in

    @property
    def deprecated(self):
        """Gets the deprecated of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The deprecated of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """Sets the deprecated of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param deprecated: The deprecated of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def description(self):
        """Gets the description of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The description of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param description: The description of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def required(self):
        """Gets the required of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The required of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param required: The required of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def content(self):
        """Gets the content of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The content of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsMediaContent
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param content: The content of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsMediaContent
        """

        self._content = content

    @property
    def example(self):
        """Gets the example of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The example of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: JavaLangObject
        """
        return self._example

    @example.setter
    def example(self, example):
        """Sets the example of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param example: The example of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: JavaLangObject
        """

        self._example = example

    @property
    def examples(self):
        """Gets the examples of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The examples of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: list[object]
        """
        return self._examples

    @examples.setter
    def examples(self, examples):
        """Sets the examples of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param examples: The examples of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: list[object]
        """

        self._examples = examples

    @property
    def explode(self):
        """Gets the explode of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The explode of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: bool
        """
        return self._explode

    @explode.setter
    def explode(self, explode):
        """Sets the explode of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param explode: The explode of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: bool
        """

        self._explode = explode

    @property
    def allow_empty_value(self):
        """Gets the allow_empty_value of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The allow_empty_value of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: bool
        """
        return self._allow_empty_value

    @allow_empty_value.setter
    def allow_empty_value(self, allow_empty_value):
        """Sets the allow_empty_value of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param allow_empty_value: The allow_empty_value of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: bool
        """

        self._allow_empty_value = allow_empty_value

    @property
    def name(self):
        """Gets the name of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The name of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param name: The name of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def style(self):
        """Gets the style of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501


        :return: The style of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :rtype: str
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.


        :param style: The style of this OrgEclipseMicroprofileOpenapiModelsParametersParameter.  # noqa: E501
        :type: str
        """
        allowed_values = ["matrix", "label", "form", "simple", "spaceDelimited", "pipeDelimited", "deepObject"]  # noqa: E501
        if style not in allowed_values:
            raise ValueError(
                "Invalid value for `style` ({0}), must be one of {1}"  # noqa: E501
                .format(style, allowed_values)
            )

        self._style = style

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsParametersParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsParametersParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
