# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsServersServerVariable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_value': 'str',
        'description': 'str',
        'enumeration': 'list[str]'
    }

    attribute_map = {
        'default_value': 'defaultValue',
        'description': 'description',
        'enumeration': 'enumeration'
    }

    def __init__(self, default_value=None, description=None, enumeration=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsServersServerVariable - a model defined in Swagger"""  # noqa: E501
        self._default_value = None
        self._description = None
        self._enumeration = None
        self.discriminator = None
        if default_value is not None:
            self.default_value = default_value
        if description is not None:
            self.description = description
        if enumeration is not None:
            self.enumeration = enumeration

    @property
    def default_value(self):
        """Gets the default_value of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501


        :return: The default_value of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """Sets the default_value of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.


        :param default_value: The default_value of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501
        :type: str
        """

        self._default_value = default_value

    @property
    def description(self):
        """Gets the description of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501


        :return: The description of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.


        :param description: The description of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def enumeration(self):
        """Gets the enumeration of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501


        :return: The enumeration of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501
        :rtype: list[str]
        """
        return self._enumeration

    @enumeration.setter
    def enumeration(self, enumeration):
        """Sets the enumeration of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.


        :param enumeration: The enumeration of this OrgEclipseMicroprofileOpenapiModelsServersServerVariable.  # noqa: E501
        :type: list[str]
        """

        self._enumeration = enumeration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsServersServerVariable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsServersServerVariable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
