# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsComponents(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'headers': 'list[object]',
        'examples': 'list[object]',
        'schemas': 'list[object]',
        'request_bodies': 'list[object]',
        'responses': 'list[object]',
        'callbacks': 'list[object]',
        'links': 'list[object]',
        'security_schemes': 'list[object]',
        'parameters': 'list[object]'
    }

    attribute_map = {
        'headers': 'headers',
        'examples': 'examples',
        'schemas': 'schemas',
        'request_bodies': 'requestBodies',
        'responses': 'responses',
        'callbacks': 'callbacks',
        'links': 'links',
        'security_schemes': 'securitySchemes',
        'parameters': 'parameters'
    }

    def __init__(self, headers=None, examples=None, schemas=None, request_bodies=None, responses=None, callbacks=None, links=None, security_schemes=None, parameters=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsComponents - a model defined in Swagger"""  # noqa: E501
        self._headers = None
        self._examples = None
        self._schemas = None
        self._request_bodies = None
        self._responses = None
        self._callbacks = None
        self._links = None
        self._security_schemes = None
        self._parameters = None
        self.discriminator = None
        if headers is not None:
            self.headers = headers
        if examples is not None:
            self.examples = examples
        if schemas is not None:
            self.schemas = schemas
        if request_bodies is not None:
            self.request_bodies = request_bodies
        if responses is not None:
            self.responses = responses
        if callbacks is not None:
            self.callbacks = callbacks
        if links is not None:
            self.links = links
        if security_schemes is not None:
            self.security_schemes = security_schemes
        if parameters is not None:
            self.parameters = parameters

    @property
    def headers(self):
        """Gets the headers of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The headers of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param headers: The headers of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._headers = headers

    @property
    def examples(self):
        """Gets the examples of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The examples of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._examples

    @examples.setter
    def examples(self, examples):
        """Sets the examples of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param examples: The examples of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._examples = examples

    @property
    def schemas(self):
        """Gets the schemas of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The schemas of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._schemas

    @schemas.setter
    def schemas(self, schemas):
        """Sets the schemas of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param schemas: The schemas of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._schemas = schemas

    @property
    def request_bodies(self):
        """Gets the request_bodies of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The request_bodies of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._request_bodies

    @request_bodies.setter
    def request_bodies(self, request_bodies):
        """Sets the request_bodies of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param request_bodies: The request_bodies of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._request_bodies = request_bodies

    @property
    def responses(self):
        """Gets the responses of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The responses of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._responses

    @responses.setter
    def responses(self, responses):
        """Sets the responses of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param responses: The responses of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._responses = responses

    @property
    def callbacks(self):
        """Gets the callbacks of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The callbacks of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._callbacks

    @callbacks.setter
    def callbacks(self, callbacks):
        """Sets the callbacks of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param callbacks: The callbacks of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._callbacks = callbacks

    @property
    def links(self):
        """Gets the links of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The links of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param links: The links of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._links = links

    @property
    def security_schemes(self):
        """Gets the security_schemes of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The security_schemes of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._security_schemes

    @security_schemes.setter
    def security_schemes(self, security_schemes):
        """Sets the security_schemes of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param security_schemes: The security_schemes of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._security_schemes = security_schemes

    @property
    def parameters(self):
        """Gets the parameters of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501


        :return: The parameters of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :rtype: list[object]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this OrgEclipseMicroprofileOpenapiModelsComponents.


        :param parameters: The parameters of this OrgEclipseMicroprofileOpenapiModelsComponents.  # noqa: E501
        :type: list[object]
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsComponents, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsComponents):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
