# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'headers': 'list[object]',
        'description': 'str',
        'links': 'list[object]',
        'content': 'OrgEclipseMicroprofileOpenapiModelsMediaContent'
    }

    attribute_map = {
        'headers': 'headers',
        'description': 'description',
        'links': 'links',
        'content': 'content'
    }

    def __init__(self, headers=None, description=None, links=None, content=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse - a model defined in Swagger"""  # noqa: E501
        self._headers = None
        self._description = None
        self._links = None
        self._content = None
        self.discriminator = None
        if headers is not None:
            self.headers = headers
        if description is not None:
            self.description = description
        if links is not None:
            self.links = links
        if content is not None:
            self.content = content

    @property
    def headers(self):
        """Gets the headers of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501


        :return: The headers of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :rtype: list[object]
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.


        :param headers: The headers of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :type: list[object]
        """

        self._headers = headers

    @property
    def description(self):
        """Gets the description of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501


        :return: The description of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.


        :param description: The description of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def links(self):
        """Gets the links of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501


        :return: The links of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :rtype: list[object]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.


        :param links: The links of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :type: list[object]
        """

        self._links = links

    @property
    def content(self):
        """Gets the content of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501


        :return: The content of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsMediaContent
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.


        :param content: The content of this OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsMediaContent
        """

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsResponsesAPIResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
