# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsServersServerVariables(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '': 'OrgEclipseMicroprofileOpenapiModelsServersServerVariable',
        'server_variable': 'OrgEclipseMicroprofileOpenapiModelsServersServerVariable',
        'server_variables': 'list[object]'
    }

    attribute_map = {
        'server_variable': 'serverVariable',
        'server_variables': 'serverVariables'
    }

    def __init__(self, server_variable=None, server_variables=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsServersServerVariables - a model defined in Swagger"""  # noqa: E501
        self._ = None
        self._server_variable = None
        self._server_variables = None
        self.discriminator = None
		
        if server_variable is not None:
            self.server_variable = server_variable
        if server_variables is not None:
            self.server_variables = server_variables


    @property
    def server_variable(self):
        """Gets the server_variable of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.  # noqa: E501


        :return: The server_variable of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsServersServerVariable
        """
        return self._server_variable

    @server_variable.setter
    def server_variable(self, server_variable):
        """Sets the server_variable of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.


        :param server_variable: The server_variable of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsServersServerVariable
        """

        self._server_variable = server_variable

    @property
    def server_variables(self):
        """Gets the server_variables of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.  # noqa: E501


        :return: The server_variables of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.  # noqa: E501
        :rtype: list[object]
        """
        return self._server_variables

    @server_variables.setter
    def server_variables(self, server_variables):
        """Sets the server_variables of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.


        :param server_variables: The server_variables of this OrgEclipseMicroprofileOpenapiModelsServersServerVariables.  # noqa: E501
        :type: list[object]
        """

        self._server_variables = server_variables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsServersServerVariables, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsServersServerVariables):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
