# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsMediaContent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '': 'OrgEclipseMicroprofileOpenapiModelsMediaMediaType',
        'media_types': 'list[object]',
        'media_type': 'OrgEclipseMicroprofileOpenapiModelsMediaMediaType'
    }

    attribute_map = {
        'media_types': 'mediaTypes',
        'media_type': 'mediaType'
    }

    def __init__(self, media_types=None, media_type=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsMediaContent - a model defined in Swagger"""  # noqa: E501
        self._ = None
        self._media_types = None
        self._media_type = None
        self.discriminator = None
        if media_types is not None:
            self.media_types = media_types
        if media_type is not None:
            self.media_type = media_type

    @property
    def media_types(self):
        """Gets the media_types of this OrgEclipseMicroprofileOpenapiModelsMediaContent.  # noqa: E501


        :return: The media_types of this OrgEclipseMicroprofileOpenapiModelsMediaContent.  # noqa: E501
        :rtype: list[object]
        """
        return self._media_types

    @media_types.setter
    def media_types(self, media_types):
        """Sets the media_types of this OrgEclipseMicroprofileOpenapiModelsMediaContent.


        :param media_types: The media_types of this OrgEclipseMicroprofileOpenapiModelsMediaContent.  # noqa: E501
        :type: list[object]
        """

        self._media_types = media_types

    @property
    def media_type(self):
        """Gets the media_type of this OrgEclipseMicroprofileOpenapiModelsMediaContent.  # noqa: E501


        :return: The media_type of this OrgEclipseMicroprofileOpenapiModelsMediaContent.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsMediaMediaType
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this OrgEclipseMicroprofileOpenapiModelsMediaContent.


        :param media_type: The media_type of this OrgEclipseMicroprofileOpenapiModelsMediaContent.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsMediaMediaType
        """

        self._media_type = media_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsMediaContent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsMediaContent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
