# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsMediaMediaType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'schema': 'OrgEclipseMicroprofileOpenapiModelsMediaSchema',
        'examples': 'list[object]',
        'encoding': 'list[object]',
        'example': 'JavaLangObject'
    }

    attribute_map = {
        'schema': 'schema',
        'examples': 'examples',
        'encoding': 'encoding',
        'example': 'example'
    }

    def __init__(self, schema=None, examples=None, encoding=None, example=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsMediaMediaType - a model defined in Swagger"""  # noqa: E501
        self._schema = None
        self._examples = None
        self._encoding = None
        self._example = None
        self.discriminator = None
        if schema is not None:
            self.schema = schema
        if examples is not None:
            self.examples = examples
        if encoding is not None:
            self.encoding = encoding
        if example is not None:
            self.example = example

    @property
    def schema(self):
        """Gets the schema of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501


        :return: The schema of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsMediaSchema
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.


        :param schema: The schema of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsMediaSchema
        """

        self._schema = schema

    @property
    def examples(self):
        """Gets the examples of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501


        :return: The examples of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :rtype: list[object]
        """
        return self._examples

    @examples.setter
    def examples(self, examples):
        """Sets the examples of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.


        :param examples: The examples of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :type: list[object]
        """

        self._examples = examples

    @property
    def encoding(self):
        """Gets the encoding of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501


        :return: The encoding of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :rtype: list[object]
        """
        return self._encoding

    @encoding.setter
    def encoding(self, encoding):
        """Sets the encoding of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.


        :param encoding: The encoding of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :type: list[object]
        """

        self._encoding = encoding

    @property
    def example(self):
        """Gets the example of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501


        :return: The example of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :rtype: JavaLangObject
        """
        return self._example

    @example.setter
    def example(self, example):
        """Sets the example of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.


        :param example: The example of this OrgEclipseMicroprofileOpenapiModelsMediaMediaType.  # noqa: E501
        :type: JavaLangObject
        """

        self._example = example

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsMediaMediaType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsMediaMediaType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
