# coding: utf-8

"""


    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgEclipseMicroprofileOpenapiModelsServersServer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'variables': 'OrgEclipseMicroprofileOpenapiModelsServersServerVariables',
        'description': 'str',
        'url': 'str'
    }

    attribute_map = {
        'variables': 'variables',
        'description': 'description',
        'url': 'url'
    }

    def __init__(self, variables=None, description=None, url=None):  # noqa: E501
        """OrgEclipseMicroprofileOpenapiModelsServersServer - a model defined in Swagger"""  # noqa: E501
        self._variables = None
        self._description = None
        self._url = None
        self.discriminator = None
        if variables is not None:
            self.variables = variables
        if description is not None:
            self.description = description
        if url is not None:
            self.url = url

    @property
    def variables(self):
        """Gets the variables of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501


        :return: The variables of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501
        :rtype: OrgEclipseMicroprofileOpenapiModelsServersServerVariables
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this OrgEclipseMicroprofileOpenapiModelsServersServer.


        :param variables: The variables of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501
        :type: OrgEclipseMicroprofileOpenapiModelsServersServerVariables
        """

        self._variables = variables

    @property
    def description(self):
        """Gets the description of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501


        :return: The description of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OrgEclipseMicroprofileOpenapiModelsServersServer.


        :param description: The description of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def url(self):
        """Gets the url of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501


        :return: The url of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this OrgEclipseMicroprofileOpenapiModelsServersServer.


        :param url: The url of this OrgEclipseMicroprofileOpenapiModelsServersServer.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgEclipseMicroprofileOpenapiModelsServersServer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgEclipseMicroprofileOpenapiModelsServersServer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
